SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'PUBLIC'
ORDER BY TABLE_NAME;

SELECT COUNT(*) AS TOTAL_CLIENTES FROM CLIENTE;

SELECT COUNT(*) AS TOTAL_SERVICOS FROM SERVICO;

SELECT COUNT(*) AS TOTAL_PROFISSIONAIS FROM PROFISSIONAL;

SELECT COUNT(*) AS TOTAL_AGENDAMENTOS FROM AGENDAMENTO;

SELECT ID, NOME, TELEFONE, EMAIL
FROM CLIENTE
ORDER BY ID
LIMIT 3;

SELECT ID, NOME, PRECO, DURACAO_MINUTOS
FROM SERVICO
ORDER BY ID
LIMIT 3;

SELECT ID, NOME, ESPECIALIDADE, ATIVO
FROM PROFISSIONAL
ORDER BY ID
LIMIT 3;

SELECT A.ID,
       C.NOME AS CLIENTE,
       S.NOME AS SERVICO,
       P.NOME AS PROFISSIONAL,
       A.DATA,
       A.HORARIO,
       A.STATUS
FROM AGENDAMENTO A
LEFT JOIN CLIENTE C ON A.CLIENTE_ID = C.ID
LEFT JOIN SERVICO S ON A.SERVICO_ID = S.ID
LEFT JOIN PROFISSIONAL P ON A.PROFISSIONAL_ID = P.ID
ORDER BY A.ID
LIMIT 5;
